### ISSUE TITLE
Do you plan to make this Vue 2.0 compatible?

### ISSUE THREAD

**Issue by irelandpaul** [CroudSupport/vue-quill#12]
Wondering if you plan to update this. Quill is a great editor. Thank you!

**Comment by BrockReece** [comment]
Hi @irelandpaul 

Thanks for the kind words. I have just started using Vue 2, so I am just getting used to it before I make any changes.
Do you have much experience with Vue 2 to offer some pointers?

Cheers
Brock

**Comment by irelandpaul** [comment]
I started with Vue 2 so I'm not sure the differences beyond what is written in the [migration guide](http://vuejs.org/guide/migration.html). I tried my hand changing the depreciated references like [v-el ](http://vuejs.org/guide/migration.html#v-el-and-v-ref-deprecated), but I did not get it working correctly. It showed up on the page but was not focusable. Before I spun my wheels too much I was going to see if you were planning on working through it.  If I do make any progress I'll let you know!

**Comment by servermachine** [comment]
I just hacked something together to start you off [here](https://gist.github.com/servermachine/f82b121910ab377047c5b123b71256f5). I commented each line I hacked.


You need to download the quill.css for 1.1.3, and update the quill module to 1.1.3

**Comment by Elhebert** [comment]
I started to work on a VueJS 2 version (and an up-to-date version of Quill).

And since Quill removed setHTML and getHTML in v1.x, a small "hack" is needed to implement the same behaviour again : `this.editor.root.innerHTML` is used to get (and set) the HTML.

You can find my _WIP version_ here : https://github.com/Elhebert/vue-quill/blob/master/src/Quill.vue

I still have to make some tweaks (and to test it all), and of course, since quite a lot change with VueJS 2, I also need to change the README, which is why I haven't made a PR yet.

**Comment by BrockReece** [comment]
I have created a new branch (vue2) that we will be merging the changes from https://github.com/CroudSupport/vue-quill/pull/13 into. 

Feel free to test this version and give feedback and when we are happy I will publish this new version to NPM.

**Comment by BrockReece** [comment]
Sorry for the stupidly long wait.
This is now vue2
